# Learn more about configuring shopify.app.toml at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "961f9c9b428a8886943d8685f7ff1074"
name = "Glamhop Returns & Exchange"
handle = "glamhop-returns-exchange"
application_url = "https://glamhop-returns-exchange.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = ""

[access_scopes]
scopes = "write_orders,read_orders,read_customers,read_products"

[auth]
redirect_urls = [
  "https://glamhop-returns-exchange.vercel.app/auth/callback",
  "https://glamhop-returns-exchange.vercel.app/auth/shopify/callback"
]

[app_proxy]
url = "https://glamhop-returns-exchange.vercel.app/app/proxy"
subpath = "returns"
prefix = "apps"

[webhooks]
api_version = "2024-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"
